name: pawsitive_adoption
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.1
  permission_handler: ^10.0.0
  rename: ^3.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
